### ISSUE TITLE
Question: what version is SD interface?

### ISSUE THREAD

**Issue by ralphhipps** [orangecrab-fpga/orangecrab-hardware#38]
any plans for 4.0 or 7.0?

**Comment by gregdavill** [comment]
The SD interface is implemented in FPGA fabric, so it's not technically limited to a specific version.
However the I/O is rated at 3.3V only, which does limit the speeds at which you can acquire, that basically limits the interface to `HS` 25MHz, and means you can't use the `UHS-I` or higher speeds (Which require switching I/O to 1.8V)
